Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/shared", type: "rsync"

  config.vm.hostname = "docker-host"

  config.ssh.insert_key = false

  config.vm.box_check_update = false
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.provision "docker"

  # The following line terminates all ssh connections. Therefore
  # Vagrant will be forced to reconnect.
  # That's a workaround to have the docker command in the PATH
  config.vm.provision "shell", inline: "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 9990, host: 9990, auto_correct: true
end
