Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |docker|
    docker.vagrant_vagrantfile = "host/Vagrantfile"

	docker.build_dir = "."

	docker.volumes = ["/shared/:/shared:rw"]
	
	docker.ports = ["8080:8080", "9990:9990"]
  end
end
